[window]

dimensions = { columns = 120, lines = 30 }

position = { x = 507, y = 0 }

opacity = 0.9

dynamic_padding = false
padding.x = 0
padding.y = 0

[terminal]

shell = "zsh"

[font]

normal.family = "JuliaMono Nerd Font Mono"

size = 13

[colors]

[colors.primary]

foreground = "#34dd34"
background = "#082208"

[colors.normal]

black = "#082208"
green = "#34dd34"
red = "#00a950"
yellow = "#98a126"
blue = "#7eb17e"
magenta = "#54b100"
cyan = "#00a950"
white = "#34dd34"

[colors.bright]

black = "#7eb17e"
green = "#34dd34"
red = "#00a950"
yellow = "#98a126"
blue = "#7eb17e"
magenta = "#54b100"
cyan = "#00a950"
white = "#34dd34"
