# environment.yaml

name: gp
channels:
  - conda-forge
dependencies:
  - pylsp-mypy
  - pynvim
  - pylint
  - flake8
  - anaconda
  - pip
  - jupyter
  - jupyterlab
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pandas
  - scikit-learn
  - statsmodels
  - linearmodels
  - spacy
  - bibtexparser
  - fastprogress
  - jupyterlab_vim
